exp_name: 'MNIST_0'
agent: 'MnistAgent'

cuda: true
seed: 1

some_model_attribute: 0

batch_size: 64
test_batch_size: 64

learning_rate: 0.0002
weight_decay: 0
beta1: 0.5
beta2: 0.999
momentum: 0.9

max_epoch: 20

validate_every: 90
log_interval: 90

save_best: True

checkpoint_file: 'checkpoint.pth.tar'
checkpoint_dir: './experiments'

data_loader": 'MnistDataLoader'
data_loader_workers: 2
pin_memory: true
async_loading: true

data_mode: 'download'
data_folder: 
  value: './data/MNIST'
